import React from 'react';
import { formatCoordinate } from '../../utils/coordinates';
import { formatTimestamp } from '../../utils/time';
function DetailRow({ label, value }) { return <div className="detail-row"><span>{label}</span><strong>{value || '—'}</strong></div>; }
export default function SatelliteDetailsPanel({ satelliteCard, selectedPoint, loading, error }) {
  if (!satelliteCard) return <section className="panel-section"><div className="section-header"><h3>Карточка спутника</h3></div><p className="muted-text">Выберите спутник в 3D, чтобы загрузить карточку, трек, зоны видимости и данные о следующем пролёте.</p></section>;
  const { current_position: position, next_pass_over_point: nextPass } = satelliteCard;
  return <section className="panel-section"><div className="section-header"><h3>Карточка спутника</h3>{loading ? <span className="status-pill">Загрузка…</span> : null}</div>{error ? <div className="error-banner">{error}</div> : null}<div className="satellite-title-block"><h2>{satelliteCard.name}</h2><p>NORAD {satelliteCard.norad_id}</p></div><div className="detail-grid"><DetailRow label="Страна" value={satelliteCard.country} /><DetailRow label="Оператор" value={satelliteCard.operator} /><DetailRow label="Орбита" value={satelliteCard.orbit_type} /><DetailRow label="Назначение" value={satelliteCard.purpose} /><DetailRow label="Высота" value={satelliteCard.approx_altitude_km ? `${satelliteCard.approx_altitude_km} км` : '—'} /><DetailRow label="Период" value={satelliteCard.period_minutes ? `${satelliteCard.period_minutes} мин` : '—'} /><DetailRow label="Скорость" value={`${formatCoordinate(position?.velocity?.speed_km_s)} км/с`} /><DetailRow label="Эпоха TLE" value={satelliteCard.latest_tle_epoch ? formatTimestamp(satelliteCard.latest_tle_epoch) : '—'} /></div>{position?.geodetic ? <div className="info-card compact-card"><h4>Текущие координаты</h4><p>Широта {formatCoordinate(position.geodetic.lat)}°, долгота {formatCoordinate(position.geodetic.lon)}°, высота {formatCoordinate(position.geodetic.alt_km)} км</p><p className="muted-text">Время: {formatTimestamp(position.timestamp)}</p></div> : null}<div className="info-card compact-card"><h4>Следующий пролёт над выбранной точкой</h4>{selectedPoint && nextPass ? <><p>Точка: {formatCoordinate(selectedPoint.lat)}°, {formatCoordinate(selectedPoint.lon)}°</p><p>Вход: {formatTimestamp(nextPass.enter_time)}</p><p>Пик: {formatTimestamp(nextPass.peak_time)}</p><p>Выход: {formatTimestamp(nextPass.exit_time)}</p><p>Минимальная дистанция: {formatCoordinate(nextPass.min_distance_km)} км</p></> : <p className="muted-text">Выберите точку на глобусе, чтобы запросить следующий пролёт.</p>}</div></section>;
}
