const fs = require('fs');
const path = require('path');

function parseEnvFile(filepath) {
  if (!fs.existsSync(filepath)) return {};
  const lines = fs.readFileSync(filepath, 'utf8').split(/\r?\n/);
  const result = {};
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eqIndex = line.indexOf('=');
    if (eqIndex === -1) continue;
    const key = line.slice(0, eqIndex).trim();
    let value = line.slice(eqIndex + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

const projectRoot = path.resolve(__dirname, '..');
const merged = {
  ...parseEnvFile(path.join(projectRoot, '.env')),
  ...parseEnvFile(path.join(projectRoot, '.env.production')),
  ...parseEnvFile(path.join(projectRoot, '.env.local')),
  ...parseEnvFile(path.join(projectRoot, '.env.production.local')),
};

const fancyValue = (process.env.FANCY ?? merged.FANCY ?? 'false').toString().trim().toLowerCase() === 'true' ? 'true' : 'false';
const targetPath = path.join(projectRoot, '.env.local');
const content = `# autogenerated by scripts/syncFancyEnv.js\nREACT_APP_FANCY=${fancyValue}\n`;
fs.writeFileSync(targetPath, content, 'utf8');
console.log(`[syncFancyEnv] FANCY=${fancyValue} -> ${path.basename(targetPath)}`);
